name: check_artisan
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  sms_autofill: ^2.4.0
  image_picker: ^0.8.5+3
  bloc: ^8.1.4
  equatable: ^2.0.5
  http: ^1.2.0
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^7.0.1
  provider: ^6.1.2
  top_snackbar_flutter: ^3.1.0
  animated_snack_bar: ^0.4.0
  pin_code_fields: ^8.0.1
  loggy: ^2.0.3
  page_transition: ^2.1.0
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.4.0
  flutter_floating_bottom_bar: ^1.2.1
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/icons/Home Screen.png
    - assets/icons/logo checkartisan 1.png
    - assets/icons/bro.png
    - assets/Buttons/Group 1.png
    - assets/icons/track.png
    - assets/icons/call.png
    - assets/icons/pana.png
    - assets/icons/reg screen.jpg
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/confirmation.png
    - assets/icons/otp.png
    - assets/icons/password_reset.png
    - assets/icons/dashboard.png
    - assets/Buttons/edit.png
    - assets/Buttons/info.png
    - assets/Buttons/logout.png
    - assets/Buttons/password.png
    - assets/Buttons/update.png
    - assets/icons/tools.png
    - assets/icons/Rectangle.png
    - assets/icons/Splash 11.png
    - assets/icons/Splash2.png
    - assets/icons/Splash3.png
    - assets/icons/home.png    
    - assets/icons/location.png
    - assets/icons/tools.png    
    - assets/icons/profile.png
    - assets/icons/1__VscKvUjc_oysnXrDwLYzQ.png
    - assets/icons/quote.png
    - assets/icons/job_list.png
    - assets/icons/new_jobs.png
    - assets/icons/reviews.png
    

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
          style: italic

flutter_native_splash:
  color: "#004D40F2"
  image: assets/icons/Home Screen.png
  fullscreen: true

